# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.runs/synth_1/as_top_mem.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.cache/wt [current_project]
set_property parent.project_path /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/abhishek-revoor/.Xilinx/Vivado/2024.2/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.1 [current_project]
set_property ip_output_repo /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/sim/riscvtest.mem
read_verilog -library xil_defaultlib -sv {
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/as_pack.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asAdd.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asAluRV.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asCPU.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asCgu.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asCguCore.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asControlAll.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asDMem.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asDMemBack.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asDMemCore.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asDMemFront.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asDecode.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asGpio.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asGpioTop.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asIMem.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asImmGen.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asMBpi.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asMux2.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asMux3.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asPC.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asRegFile.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asSBpi.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/ip_jtag/src/by_cell.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/ip_jtag/src/dr_cell.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/ip_jtag/src/dr_reg.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/ip_jtag/src/ir_cell.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/ip_jtag/src/ir_decode.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/ip_jtag/src/jtag.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/ip_jtag/src/scan_cell.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/ip_jtag/src/tap_fsm.sv
  /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/sources_1/imports/rwu-rv64i-master/src/asTopMem.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/constrs_1/imports/syn/Zybo-Master.xdc
set_property used_in_implementation false [get_files /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/constrs_1/imports/syn/Zybo-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/abhishek-revoor/Desktop/Thesis/rwu-rv64i-master/Vivado/project_3/project_3.srcs/utils_1/imports/synth_1/as_top_mem.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top as_top_mem -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef as_top_mem.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file as_top_mem_utilization_synth.rpt -pb as_top_mem_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
